source 'http://rubygems.org'

gem 'rails', '3.0.1'

gem 'mysql'
gem 'meme_generator'

group :development, :test do
  gem 'ruby-debug19'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'heroku'
  gem 'steak'
  gem 'heroku'
end
