require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MemesController do

  def mock_meme(stubs={})
    @mock_meme ||= mock_model(Meme, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all memes as @memes" do
      Meme.stub(:all) { [mock_meme] }
      get :index
      assigns(:memes).should eq([mock_meme])
    end
  end

  describe "GET show" do
    it "assigns the requested meme as @meme" do
      Meme.stub(:find).with("37") { mock_meme }
      get :show, :id => "37"
      assigns(:meme).should be(mock_meme)
    end
  end

  describe "GET new" do
    it "assigns a new meme as @meme" do
      Meme.stub(:new) { mock_meme }
      get :new
      assigns(:meme).should be(mock_meme)
    end
  end

  describe "GET edit" do
    it "assigns the requested meme as @meme" do
      Meme.stub(:find).with("37") { mock_meme }
      get :edit, :id => "37"
      assigns(:meme).should be(mock_meme)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created meme as @meme" do
        Meme.stub(:new).with({'these' => 'params'}) { mock_meme(:save => true) }
        post :create, :meme => {'these' => 'params'}
        assigns(:meme).should be(mock_meme)
      end

      it "redirects to the created meme" do
        Meme.stub(:new) { mock_meme(:save => true) }
        post :create, :meme => {}
        response.should redirect_to(meme_url(mock_meme))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved meme as @meme" do
        Meme.stub(:new).with({'these' => 'params'}) { mock_meme(:save => false) }
        post :create, :meme => {'these' => 'params'}
        assigns(:meme).should be(mock_meme)
      end

      it "re-renders the 'new' template" do
        Meme.stub(:new) { mock_meme(:save => false) }
        post :create, :meme => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested meme" do
        Meme.stub(:find).with("37") { mock_meme }
        mock_meme.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :meme => {'these' => 'params'}
      end

      it "assigns the requested meme as @meme" do
        Meme.stub(:find) { mock_meme(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:meme).should be(mock_meme)
      end

      it "redirects to the meme" do
        Meme.stub(:find) { mock_meme(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(meme_url(mock_meme))
      end
    end

    describe "with invalid params" do
      it "assigns the meme as @meme" do
        Meme.stub(:find) { mock_meme(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:meme).should be(mock_meme)
      end

      it "re-renders the 'edit' template" do
        Meme.stub(:find) { mock_meme(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested meme" do
      Meme.stub(:find).with("37") { mock_meme }
      mock_meme.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the memes list" do
      Meme.stub(:find) { mock_meme }
      delete :destroy, :id => "1"
      response.should redirect_to(memes_url)
    end
  end

end
