require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MemesController do

  describe "POST create" do
    describe "request with proper attributes" do
      before(:each) do
        params = { :meme => { :meme_type => "Y_U_NO", :first_line => "first", :second_line => "second" } }
        post :create, params.merge(:format => :json)
        @response_body = JSON.parse response.body
      end

      it "Should return 201 created" do
        response.code.should == "201"
      end

      it "Should create a meme" do
        Meme.count.should == 1
      end

      it "Should return proper image url" do
        image_url = @response_body["meme"]["image_url"]
        image_url.should be
        image_url.match(/first-second.jpg/).should be
      end
    end

    describe "not enough attributes" do
      before(:each) do
        post :create, { :format => :json }
        @response_body = JSON.parse response.body
      end

      it "Should return failed status code" do
        response.code.should == "422"
      end
    end
  end
end
